### ISSUE TITLE
Website Issue

### ISSUE THREAD

**Issue by idekwhoIam** [wwdc17/applenc#2]
As I am not sure where else to post this, I noticed on your website that in a header, you state:
### MY WORK
and in that, is the WWDC17 countdown timer, but I also noticed on your profile that you forked the repo from another user? I am no legal lawyer or anything, and I am not saying that I am by any means, but, I know that taking someone else's work and saying that it is "Your Work" is not tolerated and against Copyright Laws. I did take a look at some of the code from your fork, I didn't notice watermarks in either the forked version, nor the original repo version, but still saying that it is your work is not tolerated. And that in the footer you stated this: `© 2017 JS. All Rights Reserved.`
I also noticed in your code *via inspect element* that the website/HTML code is a W3layouts layout.
You should not state `© 2017 JS.` at all if you didn't make the website from scratch yourself. The code is watermarked with a license, you don't have those rights, W3layouts does 
`License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/`
Now, I could report this to the original author of the WWDC countdown, and the author of the website layout, and to GitHub, but I will let you decide on whether you want to fix that yourself, or whether you leave it.
# Screenshots
[![https://gyazo.com/8c966f6b7088480f21982c21810b8248](https://i.gyazo.com/8c966f6b7088480f21982c21810b8248.png)](https://gyazo.com/8c966f6b7088480f21982c21810b8248)

[![https://gyazo.com/34477a0198efe31b9ea6721ffc0b0fd3](https://i.gyazo.com/34477a0198efe31b9ea6721ffc0b0fd3.png)](https://gyazo.com/34477a0198efe31b9ea6721ffc0b0fd3)

**Comment by wwdc17** [comment]
Fuck you.

The countdown IS NOT that forked repo, it is a PRIVATE repo, access it at http://iamjulian.me/countdown - as you can see, it's not /countdown16, because /countdown16 would have been that repo.

I don't give a FUCK that it's a w3layouts, FUCK YOU TO HELL. You have no right to come here and do this shit with no proof. Live a life. Fuck you.

**Comment by wwdc17** [comment]
You have one more message before I close and lock this issue.

**Comment by wwdc17** [comment]
Oh and I just reported you @idekwhoIam

**Comment by wwdc17** [comment]
Closed, fuck you, reported, this repo will also be private. Good bye, contact me on reddit @ /u/jaspergreenham if you want.
